version: "3.8"
services:
  web:
    container_name: web
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
       db:
        condition: service_healthy
  db:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
