version: "3.8"
services:
  web:
    container_name: captsone-web
    image: ghcr.io/omegawaffle/ift-401-capstone:latest
    ports:
      - "5000:5000"
    environment:
      - SQL_HOST=${SQL_HOST}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    restart: always
    container_name: capstone-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
