apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: flask
  SQL_PASSWORD: password
  SQL_USERNAME: root
  SQL_DATABASE: flask
  SQL_HOST: mysql
  